// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlnipdcbznogoxcsifiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbmlwZGNiem5vZ294Y3NpZml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MDg1MDgsImV4cCI6MjA0OTI4NDUwOH0.40q1lIE5aIfOQ8w04EomGm85icVIi7u2zqFZMbXcLEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);